### ISSUE TITLE
Open source Virus to install latest version of firefox or chrome on Windows machine :D

### ISSUE THREAD

**Issue by raoofha** [bevry-archive/ideashare#10]
hi mr @balupton this idea just came to my mind and I thought maybe I put it in here

after couple of month of research for learning best practices in web development I found out it still painfull and it coud be very easy if everyone hase latest browser installed on their system. 

I don't know how practical or usefull it might be but it sound cool

**Comment by greduan** [comment]
@raoofha So you're suggesting a virus that would install the latest version of Chrome or Firefox whenever the user gets infected by it?

It would still be a virus though, which are unethical. :/

**Comment by raoofha** [comment]
if it really usefull and don't cause any future misuse I don't thinks it's unethical, consider it as a auto patch. maybe google, mozilla, microsoft and antivirus companies can work together and make a big announsement to make it happen. wouldn't be cool if we can use something like Object.observe in all browser right now. take a look at [reactive-coffee](http://yang.github.io/reactive-coffee/ideas.html)

**Comment by greduan** [comment]
Well usually the user only installs the browsers he wants. If he's using IE that's because he wasn't aware of the other browsers anyway. Don't get me wrong though, I hate IE. lol

However if the user does install another browser, the browser usually makes sure it's as up-to-date as possible.

**Comment by raoofha** [comment]
never mind I just post to see if this place for brain stormy things or we have to had a real practical idea because I usually have many idea in my head ( possibly not usefull or not practical ) and would love to hear others opinion

**Comment by greduan** [comment]
I think it's for both, but I think it's also more geared towards ideas that could be implemented as a product? I'm not sure. Sorry for dragging you down though. :(

**Comment by raoofha** [comment]
no problem bro :)

**Comment by balupton** [comment]
I think it is a nifty idea. Although one precaution is I doubt a Mozilla or Google would like their name attached to such a questionable initiative. Perhaps if it prompted them to pick either Firefox or Chrome, then it would be a bit less damaging to their brands.

As Microsoft are dropping Windows XP support next year, I don't think it will much longer. As well, getting people on Ubuntu for free may be a better alternative (although that would be a lot more radical change, the browser switch is one the user may not even notice) - I believe one of the European governments actually gives out free copies of Ubuntu to Windows XP users.

However, on the subject of outdated browser use. I take the stance, that the only stats being reported, are the stats of web developers testing in outdated browsers. Or in terms of big businesses only using outdated browser versions because that is what their software supports, and they prevent installation of anything else - I believe I read somewhere, this is the major cause of it, rather than individuals who have a choice.
